


















]    path('watchlist/', views.watchlistPage, name='watchlist'),    path('clear_recently_viewed/', views.clear_recently_viewed, name='clear_recently_viewed'),    path('top-50-movies/', views.getTop50movies, name='top-50-movies'),    path('search/', views.searchMovie, name='search'),    path('celebrity/<int:id>/', views.celebrity_profile, name='celebrity_profile'),    path('genre/<int:genre_id>/', views.genrePage, name='genre_movies'),    path('register/', views.registerUser, name='register'),    path('logout/', views.logoutUser, name='logout'),    path('login/', views.loginPage, name='login'),    path('save_comment/', views.save_comment, name='save_comment'),    path('room/<int:id>/', views.roomPage, name='room'),    path('remove_from_watchlist/<int:movie_id>/', views.remove_from_watchlist, name='remove_from_watchlist'),    path('add_to_watchlist/<int:movie_id>/', views.add_to_watchlist, name='add_to_watchlist'),    path('', views.homepage, name='home'),urlpatterns = [from . import viewsfrom django.urls import path